---
title: "nutrient-mvco-eml-assembly"
author: "Kate Morkeski"
date: "11/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# define source for functions developed for the EDI packaging workflow
#source("edi-utilities.R")

# define R packages to require 
require(here)
require(tidyverse)
require(readxl)
require(lubridate)
require(devtools)
require(EMLassemblyline)
require(EML)
require(maps)
require(xml2)
require(geosphere)
require(httr)

#set path to root of project
here("nes-lter-nutrient")

```

## Read in provided data
```{r}

nutrients_input <- read_excel('MVCO_nut_copy01Nov2021.xls') 


```
## Update column names

```{r}

# remove quotation marks and spaces
names(nutrients_input)<- gsub("'", "", names(nutrients_input))
names(nutrients_input)<- gsub(" ", "", names(nutrients_input))
names(nutrients_input)<- gsub("-", "", names(nutrients_input))
names(nutrients_input)<- gsub(" + ", "", names(nutrients_input))

# combine date and time
nutrients_input$Start_Date <- as.character(nutrients_input$Start_Date) 
nutrients_input$Start_Time_UTC <- as.character(nutrients_input$Start_Time_UTC)
nutrients_input$Start_Time_UTC <-gsub("1899-12-31 ", "", nutrients_input$Start_Time_UTC)
nutrients_input$datetime <- paste(nutrients_input$Start_Date, nutrients_input$Start_Time_UTC)
nutrients_input$datetime <- as.POSIXct(nutrients_input$datetime, format="%Y-%m-%d %H:%M:%OS")

# rename nutrient columns
nutrients_input <-  nutrients_input %>% 
  rename(nitrate_a = `Nut_a_uMNO2+NO3`) %>% 
  rename(nitrate_b = `Nut_b_uMNO2+NO3`) %>%
  rename(nitrate_c = `Nut_c_uMNO2+NO3`) %>%
  rename(ammonium_a = `Nut_a_uMNH4+`) %>%
  rename(ammonium_b = `Nut_b_uMNH4+`) %>%
  rename(ammonium_c = `Nut_c_uMNH4+`) %>%
  rename(silicate_a = `Nut_a_uMSiO2`) %>%
  rename(silicate_b = `Nut_b_uMSiO2`) %>%
  rename(silicate_c = `Nut_c_uMSiO2`) %>%
  rename(phosphate_a = `Nut_a_uMPO43`) %>%
  rename(phosphate_b = `Nut_b_uMPO43`) %>%
  rename(phosphate_c = `Nut_c_uMPO43`) %>%
  select(-Start_Date, -Start_Time_UTC)  %>%
  relocate(datetime, .before = Latitude)

names(nutrients_input)<- tolower(names(nutrients_input))

 
# ensure rows are in time order
nutrients_input <- nutrients_input[order(nutrients_input$datetime),]



```
## Pivot data table to handle replicates

```{r}

nitrate <- nutrients_input %>% 
 select(-ammonium_a, -ammonium_b, -ammonium_c) %>%
 select(-silicate_a, -silicate_b, -silicate_c) %>%
 select(-phosphate_a, -phosphate_b, -phosphate_c)  %>% 
 pivot_longer(cols = c(nitrate_a, nitrate_b, nitrate_c), names_to = "replicate",  values_to = "nitrate")  
nitrate$replicate <- gsub("nitrate_", "", nitrate$replicate)
  
ammonium <- nutrients_input %>% 
  select(-nitrate_a, -nitrate_b, -nitrate_c) %>%
  select(-silicate_a, -silicate_b, -silicate_c) %>%
  select(-phosphate_a, -phosphate_b, -phosphate_c) %>% 
  pivot_longer(cols = c(ammonium_a, ammonium_b, ammonium_c), names_to = "replicate",  values_to = "ammonium") 
ammonium$replicate <- gsub("ammonium_", "", ammonium$replicate)
  
silicate <- nutrients_input %>%  
  select(-nitrate_a, -nitrate_b, -nitrate_c) %>%
  select(-ammonium_a, -ammonium_b, -ammonium_c) %>%
  select(-phosphate_a, -phosphate_b, -phosphate_c) %>%
  pivot_longer(cols = c(silicate_a, silicate_b, silicate_c), names_to = "replicate",  values_to = "silicate") 
silicate$replicate <- gsub("silicate_", "", silicate$replicate)
  
phosphate <- nutrients_input %>% 
  select(-nitrate_a, -nitrate_b, -nitrate_c) %>%
  select(-ammonium_a, -ammonium_b, -ammonium_c) %>%
  select(-silicate_a, -silicate_b, -silicate_c) %>%
  pivot_longer(cols = c(phosphate_a, phosphate_b, phosphate_c), names_to = "replicate",  values_to = "phosphate")
phosphate$replicate <- gsub("phosphate_", "", phosphate$replicate)

nutrients_long <- full_join(nitrate, ammonium, by = c("event_number", "event_number_niskin", "datetime", "latitude", "longitude", "depth", "replicate"))
nutrients_long <- full_join(nutrients_long, silicate, by = c("event_number", "event_number_niskin", "datetime", "latitude", "longitude", "depth", "replicate"))
nutrients_long <- full_join(nutrients_long, phosphate, by = c("event_number", "event_number_niskin", "datetime", "latitude", "longitude", "depth", "replicate"))

```

## Read in previous MVCO nutrient package and compare to new data set

```{r}

url <- ('https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-nes.1.2&entityid=9740e9ac9cd58ed3640158fbedef8180')

httr::GET(url, write_disk(tf <- tempfile(fileext = ".csv")))
tf

nutrients_pubd <- read_csv(tf, TRUE) 


```
```{r}

# rename nutrient columns
nutrients_pubd <-  nutrients_pubd %>% 
  rename(time = 'time (UTC)') %>% 
  rename(nitrate_a = ntra_a) %>% 
  rename(nitrate_b = ntra_b) %>%
  rename(nitrate_c = ntra_c) %>%
  rename(ammonium_a = amon_a) %>%
  rename(ammonium_b = amon_b) %>%
  rename(ammonium_c = amon_c) %>%
  rename(silicate_a = slca_a) %>%
  rename(silicate_b =  slca_b) %>%
  rename(silicate_c =  slca_c) %>%
  rename(phosphate_a = phos_a) %>%
  rename(phosphate_b = phos_b) %>%
  rename(phosphate_c = phos_c) 

# ensure rows are in time order
nutrients_pubd <- nutrients_pubd[order(nutrients_pubd$time),]

```
## Pivot data table to handle replicates

```{r}

prev_nitrate <- nutrients_pubd %>% 
 select(-ammonium_a, -ammonium_b, -ammonium_c) %>%
 select(-silicate_a, -silicate_b, -silicate_c) %>%
 select(-phosphate_a, -phosphate_b, -phosphate_c)  %>% 
 pivot_longer(cols = c(nitrate_a, nitrate_b, nitrate_c), names_to = "replicate",  values_to = "nitrate")  
prev_nitrate$replicate <- gsub("nitrate_", "", prev_nitrate$replicate)
  
prev_ammonium <- nutrients_pubd %>% 
  select(-nitrate_a, -nitrate_b, -nitrate_c) %>%
  select(-silicate_a, -silicate_b, -silicate_c) %>%
  select(-phosphate_a, -phosphate_b, -phosphate_c) %>% 
  pivot_longer(cols = c(ammonium_a, ammonium_b, ammonium_c), names_to = "replicate",  values_to = "ammonium") 
prev_ammonium$replicate <- gsub("ammonium_", "", prev_ammonium$replicate)
  
prev_silicate <- nutrients_pubd %>%  
  select(-nitrate_a, -nitrate_b, -nitrate_c) %>%
  select(-ammonium_a, -ammonium_b, -ammonium_c) %>%
  select(-phosphate_a, -phosphate_b, -phosphate_c) %>%
  pivot_longer(cols = c(silicate_a, silicate_b, silicate_c), names_to = "replicate",  values_to = "silicate") 
prev_silicate$replicate <- gsub("silicate_", "", prev_silicate$replicate)
  
prev_phosphate <- nutrients_pubd %>% 
  select(-nitrate_a, -nitrate_b, -nitrate_c) %>%
  select(-ammonium_a, -ammonium_b, -ammonium_c) %>%
  select(-silicate_a, -silicate_b, -silicate_c) %>%
  pivot_longer(cols = c(phosphate_a, phosphate_b, phosphate_c), names_to = "replicate",  values_to = "phosphate")
prev_phosphate$replicate <- gsub("phosphate_", "", prev_phosphate$replicate)

nutrients_pubd_long <- full_join(prev_nitrate, prev_ammonium, by = c("event_number", "time", "latitude", "longitude", "depth", "replicate"))
nutrients_pubd_long <- full_join(nutrients_pubd_long, prev_silicate, by = c("event_number", "time", "latitude", "longitude", "depth", "replicate"))
nutrients_pubd_long <- full_join(nutrients_pubd_long, prev_phosphate, by = c("event_number", "time", "latitude", "longitude", "depth", "replicate"))

```
## Compare previous nutrients data set to new data set
```{r}

# rename nutrients columns in previously published data set
nutrients_pubd_long <-  nutrients_pubd_long %>% 
  rename(nitrate_old = nitrate) %>% 
  rename(ammonium_old = ammonium) %>%
  rename(silicate_old = silicate) %>%
  rename(phosphate_old = phosphate) 

# join old and new data sets
nutrients_compare <- left_join(nutrients_long, nutrients_pubd_long, by = c("event_number", "latitude", "longitude", "depth", "replicate"))

# compare nutrient values
nutrients_compare <- nutrients_compare  %>% 
  mutate(nitrate_diff = nitrate-nitrate_old)  %>% 
  mutate(nitrate_diff = round(nitrate_diff, 3)) %>%
  mutate(ammonium_diff = ammonium-ammonium_old)  %>% 
  mutate(ammonium_diff = round(ammonium_diff, 3))  %>% 
  mutate(phosphate_diff = phosphate-phosphate_old)  %>% 
  mutate(phosphate_diff =round(phosphate_diff, 3))  %>% 
  mutate(silicate_diff = silicate-silicate_old)  %>% 
  mutate(silicate_diff =round(silicate_diff, 3))  

# check for non-zero differences
unique(nutrients_compare$nitrate_diff)
unique(nutrients_compare$ammonium_diff)
unique(nutrients_compare$phosphate_diff)
unique(nutrients_compare$silicate_diff)

# isolate non-zero differences in new dataframe
nutrient_check <- nutrients_compare %>%
  filter(nitrate_diff != 0 | ammonium_diff != 0 | phosphate_diff != 0 | silicate_diff != 0)  
 # check these three records

```

## Check range and check for outliers
# similar to nutrient transect markdown

```{r}

#plot(pressure)

```

## EML Assembly

```{r}

#plot(pressure)

```
